added email notification for updateInternship, addInternship and addP…
GhBogdan97/collective-project-backend pull request #13
Opened 2018-11-20 20:54 UTC by DenisaPopan

…ost + endpoints for getPostsForInternship and getInternshipsForStudent

2018-11-21 19:51 UTC, GhBogdan97 requested changes

2018-11-21 19:51 UTC, GhBogdan97 commented on DatabaseAccess/EmailSender/EmailSender.cs
> +﻿using System;
fisierul asta nu cred ca ar trebui sa existe

(e in DatabaseAccess si nu prea are ce cauta acolo, are ca namespace BloodPlus.Services, mai e adaugat o data din ce vad in services/emailSender)

2018-11-21 19:51 UTC, GhBogdan97 commented on collective-project-backend/Controllers/InternshipController.cs
> +        public ActionResult<List<PostViewModel>> GetPostsForInternship(int id)
ar trebui adaugat Route("{id}/posts"), cum ai facut mai sus, sa stie de unde ia id, si sa fie mai clara ruta

2018-11-23 17:36 UTC, simonaburlacu approved these changes

2018-11-23 18:45 UTC, GhBogdan97 approved these changes

2018-11-23 18:45 UTC, merged