Endpoints for: Update Company and Add Internship
GhBogdan97/collective-project-backend pull request #5
Opened 2018-11-04 14:55 UTC by DenisaPopan

2018-11-04 18:42 UTC, GhBogdan97 requested changes

2018-11-04 18:42 UTC, GhBogdan97 commented on Services/CompanyService.cs
> +        {
o sa apara aceeasi problema pe care a avut-o si toma (nu stiu daca stii de ea :D dar l-am rugat sa te ajute), pentru ca iei in if obiectul din db, el e "urmarit" de context, iar apoi cand incerci sa ii faci update o sa dea o eroare, cum ca obiectul e "urmarit" deja. si atunci cel mai bine e sa iei obiectul din db intr-o variabila, sa verifici daca e null sau nu, apoi sa schimbi fieldurile obiectului din db la fieldurile obiectului primit, apoi faci update pe obiectul din db. am pus poza mai jos cu varianta finala de la toma

![image](https://user-images.githubusercontent.com/36417662/47968349-67129f00-e071-11e8-9145-dd416755c955.png)

2018-11-10 15:23 UTC, simonaburlacu approved these changes

2018-11-10 19:27 UTC, GhBogdan97 approved these changes

2018-11-10 19:27 UTC, merged